name: Claude Code - Fork PR Review

# This workflow handles Claude reviews for PRs from forks
# It requires manual trigger by a maintainer for security
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to review'
        required: true
        type: number
      prompt:
        description: 'Optional prompt for Claude (leave empty for default PR review)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  claude-fork-review:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR information
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_number }}
            });

            // Set outputs for later steps
            core.setOutput('head_sha', pr.data.head.sha);
            core.setOutput('base_sha', pr.data.base.sha);
            core.setOutput('pr_title', pr.data.title);
            core.setOutput('pr_body', pr.data.body);

            // Post a comment that Claude is reviewing
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.inputs.pr_number }},
              body: '🤖 Claude is reviewing this PR (triggered manually by @' + context.actor + ')...'
            });

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          # Checkout the PR's head commit
          ref: ${{ steps.pr_info.outputs.head_sha }}
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Custom prompt for PR review or use provided input
          prompt: |
            ${{ github.event.inputs.prompt || format('Review pull request #{0}: {1}\n\nPR Description:\n{2}', github.event.inputs.pr_number, steps.pr_info.outputs.pr_title, steps.pr_info.outputs.pr_body) }}

          # Claude will post the review as a comment on the PR
          pr_number: ${{ github.event.inputs.pr_number }}