name: Claude Code

# SECURITY NOTE: This workflow responds to @claude mentions in issues and PRs.
# It works with fork PRs because issue_comment, pull_request_review_comment,
# and pull_request_target events run in the base repository context with access to secrets.
# Claude only reads code and posts comments (no code execution from PRs).
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [opened, synchronize]
    # Only trigger if PR description or title contains @claude
    # This prevents automatic runs on all PRs

# Set permissions at workflow level
permissions:
  contents: write  # Changed from read to write - allows Claude to push branches and create PRs
  pull-requests: write
  issues: write
  actions: read

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))) ||
      (github.event_name == 'pull_request_target' && (contains(github.event.pull_request.body, '@claude') || contains(github.event.pull_request.title, '@claude')))
    runs-on: ubuntu-latest
    # Permissions inherited from workflow level
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # For pull_request_target, we need to checkout the PR's head
          # to review the actual PR code, not the base branch
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Optional: Give a custom prompt to Claude. If this is not specified, Claude will perform the instructions specified in the comment that tagged it.
          # prompt: 'Update the pull request description to include a summary of changes.'

          # Optional: Add claude_args to customize behavior and configuration
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/sdk#command-line for available options
          # claude_args: '--model claude-opus-4-1-20250805 --allowed-tools Bash(gh pr:*)'

